# Generated by Django 4.1.4 on 2022-12-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("codigo", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
