# Generated by Django 4.1.4 on 2022-12-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0003_voto_opcao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voto",
            name="pergunta",
        ),
        migrations.RemoveField(
            model_name="voto",
            name="pub_date",
        ),
        migrations.DeleteModel(
            name="Opcao",
        ),
    ]
