# Generated by Django 4.1.4 on 2022-12-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0005_voto_data_voto_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="voto",
            name="voto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurantes.restaurante",
            ),
            preserve_default=False,
        ),
    ]
