# Generated by Django 4.1.4 on 2022-12-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0009_escolha_vote_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="voto",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="restaurante",
        ),
        migrations.RemoveField(
            model_name="voto",
            name="voto",
        ),
        migrations.DeleteModel(
            name="Escolha",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
        migrations.DeleteModel(
            name="Voto",
        ),
    ]
