# Generated by Django 4.1.4 on 2022-12-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantes", "0011_choice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
