# Generated by Django 4.1.4 on 2022-12-19 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("voto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pergunta",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pergunta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pergunta",
            name="question",
            field=models.CharField(max_length=300),
        ),
    ]
