# Generated by Django 4.1.4 on 2022-12-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voto", "0002_pergunta_created_at_pergunta_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="escolha",
            old_name="voto",
            new_name="vote",
        ),
    ]
